openapi: 3.1.0
info:
  title: Warm House API
  version: 0.1.0
paths:
  /temp-sensors/{temp_sensor_uuid}:
    get:
      tags:
        - API
      summary: Получение информации о датчике температуры
      security:
        - HTTPBearer: []
      parameters:
        - name: temp_sensor_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: "UUID датчика температуры"
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TempSensorResponse'
        '404':
          description: Device Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
    delete:
      tags:
        - API
      summary: Удаление датчика температуры
      security:
        - HTTPBearer: [ ]
      parameters:
        - name: temp_sensor_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: "UUID датчика температуры"
      responses:
        '204':
          description: Successful Response
        '404':
          description: Device Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /temp-sensors:
    get:
      tags:
        - API
      summary: Получение списка доступных для подключения датчиков температуры
      security:
        - HTTPBearer: [ ]
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TempSensorListResponse'
    post:
      tags:
        - API
      summary: "Добавление датчика температуры в систему"
      security:
        - HTTPBearer: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TempSensorRequest'
      responses:
        '201':
          description: Sensor Created
        '404':
          description: Device Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /gates/{gate_uuid}:
    post:
      tags:
        - API
      summary: Отправка команды на ворота
      security:
        - HTTPBearer: [ ]
      parameters:
        - name: gate_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: "UUID ворот"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GateCommandRequest'
      responses:
        '202':
          description: Successful Response
        '404':
          description: Device Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
  /heat-systems/{heat_system_uuid}:
    patch:
      tags:
        - API
      summary: Обновление уставок системы обогрева
      security:
        - HTTPBearer: [ ]
      parameters:
        - name: heat_system_uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
            description: "UUID системы обогрева"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/HeatSystemRequest'
      responses:
        '202':
          description: Successful Response
        '404':
          description: Device Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundResponse'
components:
  schemas:
    NotFoundResponse:
      properties:
        details:
          type: string
          title: details
          description: "Детали ошибки"
      type: object
      title: NotFoundResponse
    TempSensorRequest:
      properties:
        model_uuid:
          type: string
          format: uuid
          title: model
          description: "Модель датчика"
        house_uuid:
          type: string
          format: uuid
          title: house
          description: "Дом, к которому подключается"
      type: object
      required:
        - model_uuid
        - house_uuid
      title: TempSensorRequest
    TempSensorResponse:
      properties:
        uuid:
          type: string
          format: uuid
          title: Uuid
          description: "UUID датчика"
        accuracy:
          type: float
          title: accuracy
          description: "Точность датчика"
        added_at:
          type: string
          format: date-time
          title: added_at
          description: "Дата и время добавления датчика в систему"
        model:
          type: string
          title: model
          description: "Модель датчика"
        status:
          type: string
          title: status
          description: "Текущий статус"
      type: object
      required:
        - uuid
        - accuracy
        - added_at
        - model
        - status
      title: TempSensorResponse
    TempSensorEntryResponse:
      properties:
        uuid:
          type: string
          format: uuid
          title: Uuid
          description: "UUID датчика"
        model:
          type: string
          title: model
          description: "Модель датчика"
    TempSensorListResponse:
      properties:
        entries:
          items:
            $ref: '#/components/schemas/TempSensorEntryResponse'
          type: array
          title: TempSensorListResponse
      type: object
      required:
        - uuid
        - accuracy
        - added_at
        - model
        - status
      title: TempSensorResponse
    GateCommandRequest:
      properties:
        command_code:
          type: string
          title: command_code
          description: "Код команды"
      type: object
      required:
        - command_code
      title: GateCommandRequest
    HeatSystemRequest:
      properties:
        current_temp:
          type: string
          title: current_temp
          description: "Температура для поддержания"
      type: object
      required:
        - command_code
      title: GateCommandRequest
