@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "User")
Container(ui, "UI", "JavaScript", "Пользовательский веб-интерфейс")
Container_Boundary(system, 'System') {
    Container(backend, "Backend", "Java", "Система управления")
    ContainerDb(db, "DB", "PostgreSQL", "База данных")
    ContainerQueue(queue, "Queue", "Kafka", "Брокер")
}
Container_Ext(devices_sensors, "Devices&Sensors", "Hardware", "Приборы&Датчики")

Rel(personAlias, ui, "Visits the website", "HTTPS")
BiRel(ui, backend, "Sends requests/Gets responses", "JSON/HTTPS")
Rel(backend, queue, "Reads from", "")
BiRel(backend, db, "CRUD", "SQL/TCP")
BiRel_R(devices_sensors, queue, "Reads from\nWrites to", "")

@enduml