@startuml C4_Elements
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

Person(personAlias, "User")
Container(ui, "UI", "JavaScript", "Пользовательский веб-интерфейс")
Container_Boundary(system, 'Теплый дом') {
    Container(api_gw, "API Gateway", "", "API шлюз")
    Container(ds_management, "Devices&Sensors Management", "Java", "Система управления устройствами")
    Container(user_management, "User Management", "Java", "Система управления пользователями")
    ContainerDb(ds_db, "DB", "PostgreSQL", "База данных")
    ContainerDb(users_db, "DB", "PostgreSQL", "База данных")

}
Container_Ext(devices_sensors, "Devices&Sensors", "Hardware", "Приборы&Датчики")

Rel(personAlias, ui, "Visits the website", "HTTPS")
BiRel(api_gw, ui, "Visits the website", "HTTPS")
BiRel(api_gw, ds_management, "Sends requests/Gets responses", "JSON/HTTPS")
BiRel(ds_management, devices_sensors, "Sends commands/Gets data")
BiRel(api_gw, user_management, "Sends requests/Gets responses", "JSON/HTTPS")
Rel(user_management, users_db, "Reads from\nWrites to")
Rel(ds_management, ds_db, "Reads from\nWrites to")



@enduml